### ISSUE TITLE
Add Cristina's FCI results as tests

### ISSUE THREAD

**Issue by lelemmen** [GQCG/ci#17]
For the aug-cc-pVQZ basis set, the following FCI energies are reported for two-electron systems.

- He: -2.902533599
- Li+: -7.252573528
- Be2+: -13.63038767

**Comment by tmhuysen** [comment]
H2 and He added.

**Comment by lelemmen** [comment]
Closing this issue and bringing it over to the GQCP issues because we're archiving this repository.
