### ISSUE TITLE
New feature: DOCI 1-RDM and 2-RDM

### ISSUE THREAD

**Issue by clanssens** [GQCG/ci#39]
Is it possible to get the 1-RDM and 2-RDM from a DOCI calculation? @lelemmen @guacke

**Comment by lelemmen** [comment]
This can be done using the following functions
`ci::DOCI::calculate1RDMs()`
`ci::DOCI::calculate2RDMs()`
and using the getters
the functions `ci::DOCI::get1RDM()` and `ci::DOCI::get2RDM()`.

**Comment by lelemmen** [comment]
The driver implemented by @guacke now adds support for requesting the 1- or 2-RDM (see PR #41).
