### ISSUE TITLE
New feature: specify number of eigenvalues/eigenvectors

### ISSUE THREAD

**Issue by clanssens** [GQCG/ci#40]
Is it possible to not only get the energy and CI coefficients from the ground state but also from the first 'n' excited states, where 'n' can be specified in the input? @lelemmen @guacke

**Comment by lelemmen** [comment]
This is not possible in the current version, but it has been planned from the start to be able to do that. For that to happen, we should extend the solvers in numopt.

**Comment by lelemmen** [comment]
@guacke Now that we have the numopt:feature/lowest_eigenpairs implemented, could you take a look at updating the driver?

**Comment by lelemmen** [comment]
Closing this issue and bringing it over to the GQCP issues because we're archiving this repository.
